### ISSUE TITLE
Check that you have actual access to the file handler path.

### ISSUE THREAD

**Issue by bitsofsteve** [ThomasMeissnerDS/ml_rapid_preprocessing#17]
https://github.com/ThomasMeissnerDS/ml_rapid_preprocessing/blob/9105fc88b7448ccf5cc569e1d60a807aa3af2e3c/main.py#L501

I think the problem might be the file path as if it's not writing then there something with the path it is supposed to dump it in. Can you try to dump it in your present working directory?

**Comment by ThomasMeissnerDS** [comment]
I removed the hard coded path to save into current directory, but it did not work out.

**Comment by ThomasMeissnerDS** [comment]
Issues was the datetime converter also converting non-datetime columns.
